name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

#      - name: Copy repository contents via scp
#        uses: appleboy/scp-action@master
#        env:
#          HOST: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.SSHKEY }}
#        with:
#          source: "."
#          target: "/home/ftpuser/ftp/sajaamax"

#      - name: Executing remote command
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.SSHKEY }}
#          script: 'cd /home/ftpuser/ftp/sajaamax && ./server_deploy.sh'

      - name: Executing remote command on iranvue server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IRANVUE_HOST }}
          USERNAME: ${{ secrets.IRANVUE_USERNAME }}
          PORT: ${{ secrets.IRANVUE_PORT }}
          KEY: ${{ secrets.IRANVUE_SSHKEY }}
          script: 'cd /var/www/sajamax-backend && ./server_deploy.sh'
